package com.rumble.battles

const val LoadingTag = "LoadingTag"
const val SwipeRefreshTag = "SwipeRefreshTag"
const val InputFieldErrorTag = "InputFieldErrorTag"
const val LoginPasswordErrorTag = "LoginPasswordErrorTag"
const val EmptyViewTag = "EmptyViewTag"
const val CancelTag = "CancelTag"
const val ChannelTopBarTag = "ChannelTopBarTag"
const val RumbleBasicTopAppBarTag = "RumbleBasicTopAppBarTag"
const val RumbleTopAppBarTag = "RumbleTopAppBarTag"
const val MyVideosTopBarTag = "MyVideosTopBarTag"
const val NotificationTopBarTag = "NotificationTopBarTag"
const val TogglePushLiveStreamTag = "TogglePushLiveStreamTag"
const val ToggleEmailNotificationTag = "ToggleEmailNotificationTag"
const val EmailFrequencyTitleTag = "EmailFrequencyTitleTag"
const val ChannelTopBarActionMenuTag = "ChannelTopBarActionMenuTag"
const val ChannelBackSplashTag = "ChannelBackSplashTag"
const val CollapsingChannelImageTag = "CollapsingChannelImageTag"
const val AlertDialogTag = "AlertDialogTag"
const val EditProfileImageTag = "EditProfileImageTag"
const val EditProfileMainActionButtonTag = "EditProfileMainActionButtonTag"
const val NotificationsSectionTag = "NotificationsSectionTag"
const val BackgroundPlaySectionTag = "BackgroundPlaySectionTag"
const val UserDetailsSectionTag = "UserDetailsSectionTag"
const val DebugSectionTag = "DebugSectionTag"
const val AppInfoSectionTag = "AppInfoSectionTag"
const val CloseAccountTextTag = "CloseAccountTextTag"
const val CloseAccountActionButtonTag = "CloseAccountActionButtonTag"
const val JoinOnLocalsViewTag = "JoinOnLocalsViewTag"
const val ShareButtonTag = "ShareButtonTag"
const val ChannelDetailsActionButtonsTag = "ChannelDetailsActionButtonsTag"
const val LikeVideTag = "LikeVideTag"
const val DislikeVideTag = "DislikeVideTag"
const val PlaybackInFeedsTag = "PlaybackInFeedsTag"

// DiscoverScreen
const val DiscoverMainContentColumn = "DiscoverMainContentColumn"

const val LiveNowLoadingTag = "LiveNowLoadingTag"
const val EditorPicksLoadingTag = "EditorPicksLoadingTag"
const val FeaturedChannelsLoadingTag = "FeaturedChannelsLoadingTag"
const val DoNotMissItLoadingTag = "DoNotMissItLoadingTag"
const val PopularVideosLoadingTag = "PopularVideosLoadingTag"

const val LiveNowErrorTag = "LiveNowErrorTag"
const val EditorPicksErrorTag = "EditorPicksErrorTag"
const val FeaturedChannelsErrorTag = "FeaturedChannelsErrorTag"
const val DoNotMissItErrorTag = "DoNotMissItErrorTag"
const val PopularVideosErrorTag = "PopularVideosErrorTag"

const val LiveNowRowTag = "LiveNowRowTag"
const val SimpleVideoViewTag = "SimpleVideoViewTag"
const val EditorPicksContentTag = "EditorPicksContentTag"
const val DoNotMissItContentTag = "DoNotMissItContentTag"
const val PopularVideosContentTag = "PopularVideosTag"

// region Test Tags for Automation
//Authorization
const val AuthSignUp = "AuthSignUp"
const val AuthSignIn = "AuthSignIn"
const val AuthResetPass = "AuthResetPass"
const val AuthUsername = "AuthUsername"
//Content
const val VideoDetails = "VideoDetails"
const val VideoPlayerViewTag = "VideoPlayerView"
const val CategoriesBrowse = "CategoriesBrowse"
const val CategoryTag = "Category"
const val RecommendedChannelsTag = "RecommendedChannels"
const val VideosListTag = "VideosList"
const val ChannelDetailsTag = "ChannelDetails"
const val FeedTag = "Feed"
const val DiscoverTag = "Discover"
const val DiscoverPlayerTag = "DiscoverPlayer"
//Search
const val SearchFiltersTag = "SearchFilters"
const val SearchVideosTag = "SearchVideos"
const val SearchChannelsTag = "SearchChannels"
const val SearchCombinedTag = "SearchCombined"
const val SearchQueryTag = "SearchQuery"
//User Data
const val ProfileMenuTag = "ProfileMenu"
const val MyVideosTag = "MyVideos"
const val CreditsTag = "Credits"
const val CountryPickerTag = "CountryPicker"
const val SettingsSubdomainTag = "SettingsSubdomain"
const val SettingsEmailTag = "SettingsEmail"
const val SettingsPasswordTag = "SettingsPassword"
const val CloseAccountTag = "CloseAccount"
const val SettingsUploadingQualityTag = "SettingsUploadingQuality"
const val SubscriptionsTag = "Subscriptions"
const val NotificationsTag = "Notifications"
const val ReferralsTag = "Referrals"
const val EarningsTag = "Earnings"
const val EditProfileTag = "EditProfile"
const val SettingsTag = "Settings"
//Video Uploading
const val UploadCameraTag = "UploadCamera"
const val UploadVisibilityTag = "UploadVisibility"
const val UploadChannelTag = "UploadChannel"
const val UploadForm2Tag = "UploadForm2"
const val UploadForm1Tag = "UploadForm1"
const val UploadPreviewTag = "UploadPreview"
const val UploadGalleryTag = "UploadGallery"
const val UploadLicenseTag = "UploadLicense"
const val UploadScheduleTag = "UploadSchedule"
//Navigation
const val TabBarTag = "TabBar"
//Other
const val PremiumPromoTag = "PremiumPromo"
const val PremiumTag = "Premium"
const val MatureContentPopupTag = "MatureContentPopup"
const val LocalsPopupTag = "LocalsPopup"
const val FeedHintsTag = "FeedHints"
//Comments
const val PaidRantTag = "PaidRant"
//Misc
const val AuthSignInLoginInput = "AuthSignIn_LoginInput"
const val AuthSignInPasswordInput = "AuthSignIn_PasswordInput"
const val AuthSignInSignInButton = "AuthSignIn_SignInButton"
//Temp Tags for setting up automation
const val ContentDescriptionProfileMenuTag = "ProfileMenu"
const val AndroidIdSettingsTag = "android:id/`Settings`"
// endregion
